# Generated by Django 3.0.8 on 2020-07-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Job Seeker', 'Job Seeker'), ('Employer', 'Employer')], max_length=20, null=True, verbose_name='account type'),
        ),
    ]
