# Generated by Django 3.0.8 on 2020-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200711_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='contact country code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number'),
        ),
    ]
