# Generated by Django 3.0.8 on 2020-07-23 19:46

import accounts.utils
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200713_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('tools_used', models.TextField(blank=True, max_length=1000, null=True, verbose_name='tools Used')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('short_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='short description')),
                ('features', models.TextField(blank=True, null=True, verbose_name='features')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='job title')),
                ('company', models.CharField(max_length=150, verbose_name='company')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('country', models.CharField(blank=True, max_length=60, null=True, verbose_name='country')),
                ('company_business', models.CharField(max_length=100, verbose_name='company business')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('responsibilities', models.CharField(max_length=255, verbose_name='responsibilities')),
                ('area_of_experience', models.CharField(max_length=255, verbose_name='area of experience')),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Third Party', 'Third Party')], max_length=100, verbose_name='employment type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, verbose_name='is current')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('institute', models.CharField(max_length=255, verbose_name='institute')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('country', models.CharField(max_length=60, verbose_name='country')),
                ('topics_covered', models.CharField(max_length=255, verbose_name='topics covered')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_currently_enrolled', models.BooleanField(default=False, verbose_name='is currently enrolled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('experience', models.CharField(choices=[('Less Than 1 Year', 'Less Than 1 Year'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('6 Years', '6 Years'), ('7 Years', '7 Years'), ('8 Years', '8 Years'), ('9 Years', '9 Years'), ('10 Years', '10 Years'), ('11 Years', '11 Years'), ('12 Years', '12 Years'), ('13 Years', '13 Years'), ('14 Years', '14 Years'), ('15 Years', '15 Years'), ('16 Years', '16 Years'), ('17 Years', '17 Years'), ('18 Years', '18 Years'), ('19 Years', '19 Years'), ('20 Years+', '20 Years+')], max_length=100, verbose_name='experience in year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('about', models.TextField(blank=True, max_length=1000, null=True, verbose_name='about')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('relation', models.CharField(max_length=100, verbose_name='relation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('url', models.URLField(verbose_name='url')),
                ('date_published', models.DateField(verbose_name='date published')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('file', models.FileField(upload_to=accounts.utils.upload_project_files_path, verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attachments', to='accounts.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Project Attachment',
                'verbose_name_plural': 'Project Attachments',
                'ordering': ['-project__profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('url', models.URLField(verbose_name='url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_resource_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Online Resource',
                'verbose_name_plural': 'Online Resources',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='language')),
                ('proficiency', models.CharField(choices=[('Basic Knowledge', 'Basic Knowledge'), ('Conversant', 'Conversant'), ('Proficient', 'Proficient'), ('Fluent', 'Fluent'), ('Native', 'Native'), ('Bilingual', 'Bilingual')], max_length=100, verbose_name='proficiency')),
                ('listening', models.CharField(choices=[('Novice', 'Novice'), ('Intermidiate', 'Intermidiate'), ('Advanced', 'Advanced'), ('Superior', 'Superior')], max_length=50, verbose_name='listening')),
                ('speaking', models.CharField(choices=[('Novice', 'Novice'), ('Intermidiate', 'Intermidiate'), ('Advanced', 'Advanced'), ('Superior', 'Superior')], max_length=50, verbose_name='speaking')),
                ('reading', models.CharField(choices=[('Novice', 'Novice'), ('Intermidiate', 'Intermidiate'), ('Advanced', 'Advanced'), ('Superior', 'Superior')], max_length=50, verbose_name='reading')),
                ('writing', models.CharField(choices=[('Novice', 'Novice'), ('Intermidiate', 'Intermidiate'), ('Advanced', 'Advanced'), ('Superior', 'Superior')], max_length=50, verbose_name='writing')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Language Proficiency',
                'verbose_name_plural': 'Language Proficiencies',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_education', models.CharField(choices=[('Vocational', 'Vocational'), ('High School', 'High School'), ('Associate', 'Associate'), ('Bachelors', 'Bachelors'), ('Post Masters, Pre Doctorate', 'Post Masters, Pre Doctorate'), ('Pre Bachelors', 'Pre Bachelors'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('MBA', 'MBA'), ('Post Bachelors, Pre Masters', 'Post Bachelors, Pre Masters'), ('Military Service', 'Military Service')], max_length=100, verbose_name='level of education')),
                ('institute', models.CharField(max_length=255, verbose_name='institute')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('country', models.CharField(blank=True, max_length=60, null=True, verbose_name='country')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='field of study')),
                ('result', models.CharField(blank=True, choices=[('First Division/Class', 'First Division/Class'), ('Second Division/Class', 'Second Division/Class'), ('Third Division/Class', 'Third Division/Class'), ('Grade', 'Grade'), ('Appeared', 'Appeared'), ('Enrolled', 'Enrolled'), ('Awarded', 'Awarded'), ('Pass', 'Pass'), ('Do not mention', 'Do not mention')], max_length=100, null=True, verbose_name='result')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('achievement', models.CharField(blank=True, max_length=255, null=True, verbose_name='achievement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CareerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(blank=True, max_length=1000, null=True, verbose_name='career objective')),
                ('present_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='present designation')),
                ('desired_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='desired designation')),
                ('present_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='present salary')),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='desired salary')),
                ('desired_salary_currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='desired salary currency')),
                ('desired_salary_schedule', models.CharField(blank=True, choices=[('Year', 'Year'), ('Month', 'Month'), ('Week', 'Week'), ('Day', 'Day'), ('Hour', 'Hour')], max_length=50, null=True, verbose_name='desired salary schedule')),
                ('present_job_level', models.CharField(blank=True, choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Top Level', 'Top Level')], max_length=100, null=True, verbose_name='present job level')),
                ('desired_job_level', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Top Level', 'Top Level')], max_length=255, null=True, verbose_name='desired job level')),
                ('present_employment_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Third Party', 'Third Party')], max_length=100, null=True, verbose_name='present employment type')),
                ('desired_employment_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Third Party', 'Third Party')], max_length=255, null=True, verbose_name='present employment type')),
                ('special_qualification', models.TextField(blank=True, max_length=500, null=True, verbose_name='special qualification')),
                ('willing_to_relocate', models.BooleanField(default=False, verbose_name='willing to relocate')),
                ('willing_to_travel', models.BooleanField(default=False, verbose_name='willing to travel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Career Information',
                'verbose_name_plural': 'Career Information',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('date_awarded', models.DateField(verbose_name='date awarded')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_profile', to='accounts.UserProfile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['-profile__user__date_joined'],
            },
        ),
    ]
