import 'package:flutter/material.dart';

List bloodGroupChoicesDataSource = [
  {"display": "A+", "value": "A+"},
  {"display": "A-", "value": "A-"},
  {"display": "B+", "value": "B+"},
  {"display": "B-", "value": "B-"},
  {"display": "O+", "value": "O+"},
  {"display": "O-", "value": "O-"},
  {"display": "AB+", "value": "AB+"},
  {"display": "AB-", "value": "AB-"},
];

List genderChoicesDataSource = [
  {"display": "Male", "value": "Male"},
  {"display": "Female", "value": "Female"},
  {"display": "Other", "value": "Other"},
];

List maritalStatusChoicesDataSource = [
  {"display": "Single", "value": "Single"},
  {"display": "Married", "value": "Married"},
  {"display": "Widowed", "value": "Widowed"},
  {"display": "Divorced", "value": "Divorced"},
  {"display": "Separated", "value": "Separated"},
];

// form controllers

final firstNameController = TextEditingController();
final lastNameController = TextEditingController();
final contactController = TextEditingController();
final addressController = TextEditingController();
final cityController = TextEditingController();
final stateController = TextEditingController();
final zipCodeController = TextEditingController();
final countryController = TextEditingController();
final religionController = TextEditingController();
final aboutController = TextEditingController();

dynamic firstNameFocusNode = FocusNode();
dynamic lastNameFocusNode = FocusNode();
dynamic genderFocusNode = FocusNode();
dynamic dobFocusNode = FocusNode();
dynamic bloodGroupFocusNode = FocusNode();
dynamic contactFocusNode = FocusNode();
dynamic addressFocusNode = FocusNode();
dynamic cityFocusNode = FocusNode();
dynamic stateFocusNode = FocusNode();
dynamic zipCodeFocusNode = FocusNode();
dynamic countryFocusNode = FocusNode();
dynamic religionFocusNode = FocusNode();
dynamic maritalStatusFocusNode = FocusNode();
dynamic aboutFocusNode = FocusNode();

Map<String, dynamic> userProfileFieldProperties = {
  'user__first_name': {
    'fieldName': 'first_name',
    'isRequired': false,
    'displayName': 'First Name',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your first name',
    'helperText': null,
    'isText': true,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': firstNameController,
    'isEditable': false,
    'focusNode': firstNameFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'user__last_name': {
    'fieldName': 'last_name',
    'isRequired': false,
    'displayName': 'Last Name',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your last name',
    'helperText': null,
    'isText': true,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': lastNameController,
    'isEditable': false,
    'focusNode': lastNameFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'gender': {
    'fieldName': 'gender',
    'isRequired': false,
    'displayName': 'Gender',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': "Select your gender",
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': true,
    'dropdownDataSource': genderChoicesDataSource,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': null,
    'isEditable': false,
    'focusNode': genderFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'dob': {
    'fieldName': 'dob',
    'isRequired': false,
    'displayName': 'Date of birth',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': null,
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': true,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': null,
    'isEditable': false,
    'focusNode': dobFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'blood_group': {
    'fieldName': 'blood_group',
    'isRequired': false,
    'displayName': 'Blood Group',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': "Select your blood group",
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': true,
    'dropdownDataSource': bloodGroupChoicesDataSource,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': null,
    'isEditable': false,
    'focusNode': bloodGroupFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'profile_get_contact_number': {
    'fieldName': 'profile_get_contact_number',
    'isRequired': false,
    'displayName': 'Contact Number',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your contact number',
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': true,
    'isCountryField': false,
    'displayTogether': false,
    'controller': contactController,
    'isEditable': false,
    'focusNode': contactFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'contact_country_code': {
    'fieldName': 'contact_country_code',
    'isRequired': false,
    'displayName': 'contact_country_code',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'contact_country_code',
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': true,
    'isCountryField': false,
    'displayTogether': false,
    'controller': contactController,
    'isEditable': false,
    'focusNode': contactFocusNode,
    'value': null,
    'hiddenField': true,
    'selectedCode': null,
  },
  'contact_number': {
    'fieldName': 'contact_number',
    'isRequired': false,
    'displayName': 'contact_number',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'contact_number',
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': true,
    'isCountryField': false,
    'displayTogether': false,
    'controller': contactController,
    'isEditable': false,
    'focusNode': contactFocusNode,
    'value': null,
    'hiddenField': true,
  },
  'address': {
    'fieldName': 'address',
    'isRequired': false,
    'displayName': 'Address',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your address',
    'helperText': null,
    'isText': true,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': true,
    'controller': addressController,
    'isEditable': false,
    'focusNode': addressFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'city': {
    'fieldName': 'city',
    'isRequired': false,
    'displayName': 'City',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your city',
    'helperText': null,
    'isText': true,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': true,
    'controller': cityController,
    'isEditable': false,
    'focusNode': cityFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'state': {
    'fieldName': 'state',
    'isRequired': false,
    'displayName': 'State',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your state',
    'helperText': null,
    'isText': true,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': true,
    'controller': stateController,
    'isEditable': false,
    'focusNode': stateFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'zip_code': {
    'fieldName': 'zip_code',
    'isRequired': false,
    'displayName': 'Zip Code',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your zip code',
    'helperText': null,
    'isText': true,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': zipCodeController,
    'isEditable': false,
    'focusNode': zipCodeFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'country': {
    'fieldName': 'country',
    'isRequired': false,
    'displayName': 'Country',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your country',
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': true,
    'displayTogether': true,
    'controller': countryController,
    'isEditable': false,
    'focusNode': countryFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'religion': {
    'fieldName': 'religion',
    'isRequired': false,
    'displayName': 'Religion',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter your religion',
    'helperText': null,
    'isText': true,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': religionController,
    'isEditable': false,
    'focusNode': religionFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'marital_status': {
    'fieldName': 'marital_status',
    'isRequired': false,
    'displayName': 'Marital Status',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Select you marital status',
    'helperText': null,
    'isText': false,
    'isTextArea': false,
    'isRichText': false,
    'isDropdown': true,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': null,
    'dropdownDataSource': maritalStatusChoicesDataSource,
    'isEditable': false,
    'focusNode': maritalStatusFocusNode,
    'value': null,
    'hiddenField': false,
  },
  'about': {
    'fieldName': 'about',
    'isRequired': false,
    'displayName': 'About',
    'fieldStatus': true,
    'fieldMessage': '',
    'isChanged': false,
    'prefixText': null,
    'prefixIcon': null,
    'hintText': 'Enter more about you',
    'helperText': null,
    'isText': true,
    'isTextArea': true,
    'isRichText': false,
    'isDropdown': false,
    'isDate': false,
    'isPhoneField': false,
    'isCountryField': false,
    'displayTogether': false,
    'controller': aboutController,
    'isEditable': false,
    'focusNode': aboutFocusNode,
    'value': null,
    'hiddenField': false,
  },
};
